version = 0.1
[default.deploy.parameters]
stack_name = "bff-demo"
resolve_s3 = true
s3_prefix = "bff-demo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
